# Generated by Django 4.2.20 on 2025-05-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onebowl_app', '0003_remove_recipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
