# Generated by Django 4.2.20 on 2025-05-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onebowl_app', '0004_recipe_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_name',
            new_name='name',
        ),
    ]
