# Generated by Django 4.2.20 on 2025-05-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onebowl_app', '0005_rename_recipe_name_recipe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='img_url',
        ),
    ]
