# Generated by Django 4.2.20 on 2025-05-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onebowl_app', '0006_remove_recipe_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='onebowl_app.ingredient'),
        ),
    ]
