# Generated by Django 4.2.20 on 2025-05-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onebowl_app', '0010_remove_recipe_ingredients_delete_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img_url',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
